<a href="https://colab.research.google.com/github/DataSciLearner/PythonPractice/blob/master/create_2D_numpy_arrays_with_random_values.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
rng = np.random.RandomState(0)
x = rng.randint(10, size = (3,4))
print(x)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


In [5]:
rand = np.random.RandomState(0)
x = rand.randint(0,10,(4,6))
print(x)

[[5 0 3 3 7 9]
 [3 5 2 4 7 6]
 [8 8 1 6 7 7]
 [8 1 5 9 8 9]]


In [12]:
np.random.RandomState.randint?

Object `randint` not found.
