### Generate random integers between 0 and 9

In [10]:
from random import randrange, randint, uniform

# randrange or randint gives integral value
irand = randrange(0, 10)
irand2 = randint(0, 10)

# uniform gives float value
frand = uniform(0,10)

print(irand)
print(irand2)
print(frand)

3
2
5.359305483083082


In [5]:
from random import randrange
print(randrange(10))

3


Just a note, these are pseudorandom numbers and they are not cryptographically secure. Do not use this in any case where you don't want an attacker to guess your numbers. Use the secrets module for better random numbers.
Note that the secrets module was first added to Python in version 3.6 

In [6]:
import secrets
secrets.randbelow(10)

5

### To generate a list of 10 pseudorandom integers between 0 to 9 inclusive

In [13]:
from random import randint
x = [randint(0, 9) for p in range(0,10)]
print(x)

[2, 3, 9, 3, 8, 4, 5, 3, 0, 1]


In [17]:
# Using numpy
import numpy as np 
np.random.randint(10, size = (1, 10))

array([[3, 7, 1, 2, 1, 8, 2, 9, 0, 9]])

### Generate a list of 10 pseudorandom float numbers between 0 to 9 inclusive

In [14]:
from random import uniform
y = [uniform(0,9) for p in range(0,10)]
print(y)

[8.001707267214693, 7.911892695507109, 7.56685002191508, 2.0931116704339217, 2.2421496653079354, 4.3049354996736175, 5.166779399586636, 2.367658162576844, 6.766253263026746, 6.3952938904209935]


### Demonstrate the various random methods

In [26]:
import random
lo = 0
hi = 10
size = 5

A = [lo + int(random.random() * (hi - lo)) for _ in range(size)]
print(A)

B = [random.randint(lo, hi) for _ in range(size)]
print(B)

C = [random.randrange(lo, hi) for _ in range(size)]
print(C)

D = [random.choice(range(lo, hi)) for _ in range(size)]
print(D)

E = [random.choices(range(lo, hi), k=size)]
print(E)

F = np.random.normal(loc=5, scale=10, size=size).astype(int)
print(F)

G = np.random.poisson(lam=1, size=size).astype(int)
print(G)

H = np.random.lognormal(mean=0.0, sigma=1.0, size=size).astype(int)
print(H)

# also there is random.shuffle
lst = list(range(lo, hi))
random.shuffle(lst)
S = [lst[i] for i in range(size)]
print(S)

[4, 7, 4, 2, 1]
[0, 9, 2, 10, 8]
[4, 3, 2, 7, 9]
[1, 5, 4, 7, 6]
[[4, 0, 9, 0, 6]]
[20 14  0 12 -1]
[0 2 1 2 0]
[ 2  0 13  1  1]
[8, 5, 7, 0, 1]
